### ISSUE TITLE
Step "one level back"?

### ISSUE THREAD

**Issue by jmuheim** [nixme/pry-nav#15]
I'm quite new to console debugging. Is there a way to step "one level back"? So e.g. when I'm in a big method and I want to step out of it, instead of hitting s again and again until I'm at the end, I'd like to hit a key one time to step out. Is this already possible? Thanks.

**Comment by AndrewLngdn** [comment]
@deathweaselx86 let me know if you find an implementation, I'm messing around with it right now but it's not at the top of my priority list
