### ISSUE TITLE
Installing pry-nav makes pry croak with "SystemStackError"

### ISSUE THREAD

**Issue by rcs** [nixme/pry-nav#17]
$ pry
Loading pryrc
[1] pry(main)> ^D
$ gem install pry-nav
Fetching: pry-nav-0.2.2.gem (100%)
Successfully installed pry-nav-0.2.2
1 gem installed
$ pry
/Users/rcs/Developer/.rbenv/versions/1.9.3-p125/bin/pry:19: stack level too deep (SystemStackError)
$ gem uninstall pry-nav
Successfully uninstalled pry-nav-0.2.2
$ pry
Loading pryrc
[1] pry(main)> ^D
$

**Comment by iloveitaly** [comment]
I've never run into this, and it's a very old issue. Closing this out.
