### ISSUE TITLE
Can't escape from eval with next

### ISSUE THREAD

**Issue by sam452** [nixme/pry-nav#20]
I believe I've followed the steps to plug in pry-nav into my Gemfile in Rails. As a plug-in to pry, I'm unaware of anything else to do but 'next' yields this syntax error. 'step' yields undefined local variable for 'step.' I've found nothing else on Google of what I'm missing.

**Comment by Kshitij-Banerjee** [comment]
In my case, pry did not have the next command and was using the ruby method. 

check that next command is present in Pry.commands

**Comment by GosuSheep** [comment]
I have switched to pry-debugger and it was also throwing this error.

I checked Pry.commands during execution and like @Kshitij-Banerjee pointed out, I didn't have the 'next' or 'step' commands.

I added `gem 'pry'` and `gem 'pry-debugger'` (even though nowhere in the documentation did it suggest this). Ran a `bundle install`, and when I ran Pry.commands again, next was there! And `next` indeed worked!

**Comment by Kshitij-Banerjee** [comment]
@GosuSheep nice.

**Comment by mpelzsherman** [comment]
Hit the same issue with ruby 2.2.1. Replacing `gem 'pry'` with `gem 'pry-byebug'` worked for me.

**Comment by matthewbga** [comment]
Yes, same here.

**Comment by xasos** [comment]
+1
