### ISSUE TITLE
Release 0.2.5 with pry <12 support?

### ISSUE THREAD

**Issue by flyinbutrs** [nixme/pry-nav#30]
It appears that an MR was accepted from rrosenblum to bump the pry version support, but a release wasn't done, so rubygems.org isn't up to date. Can this be version bumped and released?

**Comment by krzysiekpom** [comment]
@nixme, can we please do that? It would make my life (and probably not only mine) a bit easier :)

**Comment by Adithya-copart** [comment]
Yes please!

**Comment by nixme** [comment]
Released as 0.3.0. Please try and let me know.

https://rubygems.org/gems/pry-nav/
