### ISSUE TITLE
stuck on old version of pry

### ISSUE THREAD

**Issue by sshock** [nixme/pry-nav#38]
pry-nav depends on pry version < 0.13, which prevents us from getting this fix:

https://github.com/pry/pry/issues/2097

Can pry-nav be updated to use a newer pry or should I switch to some other gem to provide a pry with step-by-step debugging functionality?

Thanks!

**Comment by iloveitaly** [comment]
@sshock this is fixed on master, give it a try and let me know what you think! We'll release a new version via rubygems soon.

**Comment by sshock** [comment]
@iloveitaly Looks good.  That solved the dependency issue for me, thanks!

**Comment by igorpetuh** [comment]
> @sshock this is fixed on master, give it a try and let me know what you think! We'll release a new version via rubygems soon.

Looking forward to see new version in rubygems

**Comment by kimyu92** [comment]
@iloveitaly any ETA for github tag release and availability in rubygems?

**Comment by iloveitaly** [comment]
@kimyu92 Working with @nixme on getting rubygems access.

**Comment by iloveitaly** [comment]
Just pushed 1.0.0! https://rubygems.org/gems/pry-nav/versions/1.0.0
